Implemented Discovery Server for local participant
eProsima/databroker pull request #10
Opened 2021-09-20 09:31 UTC by rsanchez15

2021-09-20 10:11 UTC, jparisu requested changes

2021-09-20 10:11 UTC, jparisu commented on src/cpp/DataBrokerConfiguration.cpp
> +                if (config_node["local-discovery"]["kind"].as<std::string>() == "discovery-server")
try not to rely in strings that set the type

2021-09-20 10:11 UTC, jparisu commented on src/cpp/DataBrokerConfiguration.cpp
> +            }
If guid will not be set here, do not store it in the configuration and use always the default one. I would suggest to give the option to set it here and use `ROS_DISCOVERY_SERVER_GUID` as default (to make it more configurable)(use WAN configuration to copy `listening-addresses` configuration parser)

2021-09-23 06:09 UTC, rsanchez15 commented on src/cpp/DataBrokerWANParticipant.cpp
> +    // pqos.wire_protocol().builtin.discovery_config.leaseDuration = fastrtps::c_TimeInfinite;
Let keep the default values:
 - Lease duration 20s
 - Announcement period 3s

2021-09-23 06:58 UTC, rsanchez15 commented on src/cpp/DataBrokerConfiguration.cpp
> +            }
Not for the PoC version

2021-09-23 08:43 UTC, jparisu requested changes
Add this new feature to the example configuration file

2021-09-23 08:43 UTC, jparisu commented on include/databroker/DataBrokerConfiguration.hpp
> +    eprosima::fastrtps::rtps::GuidPrefix_t server_guid;
```suggestion
    std::vector<Address> listening_addresses;
```
I would erase those as they are not parameters, but are always the same value depending on `discovery_server`

2021-09-23 08:43 UTC, jparisu commented on src/cpp/DataBrokerConfiguration.cpp
> +                    if (empty_listening_addresses)
```suggestion
                    if (configuration.local_configuration.listening_addresses.empty())
```

2021-09-23 08:43 UTC, jparisu commented on src/cpp/DataBrokerLocalParticipant.cpp
> +                fastrtps::rtps::DiscoveryProtocol::SERVER;
You have the variable in the configuration and you don't even use it :crying_cat_face:

2021-09-23 13:06 UTC, jparisu approved these changes
LGTM

2021-09-23 13:06 UTC, merged