Implement Bridge
eProsima/databroker pull request #34
Opened 2021-11-08 08:58 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-11-10 09:56 UTC, rsanchez15 requested changes

2021-11-10 09:56 UTC, rsanchez15 commented on include/databroker/communication/Bridge.hpp
> +    //! Destroyer
Too aggressive :joy:

2021-11-10 09:56 UTC, rsanchez15 commented on include/databroker/communication/Bridge.hpp
> +     * @param topic: Topic that this Bridge manage communication
```suggestion
     * @param topic: Topic of which this Bridge manages communication
```

2021-11-10 09:56 UTC, rsanchez15 commented on include/databroker/communication/Bridge.hpp
> +     * Topic that this bridge manage communication
```suggestion
     * Topic of which this Bridge manages communication
```

2021-11-11 09:55 UTC, jparisu commented on include/databroker/communication/Bridge.hpp
> +    //! Destroyer
:boom:

2021-11-11 09:56 UTC, jparisu commented on include/databroker/communication/Bridge.hpp
> +     * @param topic: Topic that this Bridge manage communication
:+1:

2021-11-11 09:56 UTC, jparisu commented on include/databroker/communication/Bridge.hpp
> +     * Topic that this bridge manage communication
:+1:

2021-11-11 15:04 UTC, rsanchez15 approved these changes
LGTM

2021-11-11 15:19 UTC, merged