Track implementation
eProsima/databroker pull request #35
Opened 2021-11-08 15:30 UTC by jparisu

Merge after #34

2021-11-10 10:51 UTC, rsanchez15 commented on include/databroker/communication/Track.hpp
> +     * Callback that will be called for the reader in case there are available data to read.
```suggestion
Callback that will be called by the reader in case there are available data to read.
```

2021-11-10 11:55 UTC, rsanchez15 requested changes

2021-11-11 10:03 UTC, jparisu commented on include/databroker/communication/Track.hpp
> +     * Callback that will be called for the reader in case there are available data to read.
:+1:

2021-11-11 10:03 UTC, jparisu commented on include/databroker/communication/Track.hpp
> +     * Callback that will be called fwhen there are no more data available to read.
:+1:

2021-11-12 06:34 UTC, rsanchez15 approved these changes
LGTM

2021-11-12 06:35 UTC, merged