Unblock topic
eProsima/databroker pull request #7
Opened 2021-09-01 10:32 UTC by rsanchez15

2021-09-02 14:27 UTC, jparisu requested changes

2021-09-02 14:27 UTC, jparisu commented on src/cpp/DataBrokerListener.cpp
> +        topics_blocked_.erase(topic);
erase does not fail if the element does not exist. Could skip the `find` part

2021-09-02 14:27 UTC, jparisu commented on include/databroker/DataBrokerConfiguration.hpp
> +            const std::string& file_path);
This string could be get from the configuration that is being used.

2021-09-02 14:27 UTC, jparisu commented on src/cpp/DataBrokerConfiguration.cpp
> +    configuration.config_file = file_path;
This is probably redundant and could be avoided as the argument to the function

2021-09-02 14:46 UTC, jparisu commented on src/cpp/DataBrokerListener.cpp
> +        topics_blocked_.erase(topic);
:+1:

2021-09-02 14:47 UTC, jparisu commented on include/databroker/DataBrokerConfiguration.hpp
> +            const std::string& file_path);
:+1:

2021-09-03 05:47 UTC, rsanchez15 reviewed
LGTM

2021-09-03 06:35 UTC, jparisu approved these changes
LGTM

2021-09-03 06:37 UTC, merged